import os, sys, subprocess, json

# ---------------------------------------------------------------------------
# Dependency bootstrap
# ---------------------------------------------------------------------------
def install_deps():
    print("[SETUP] Installing Python dependencies...")
    # Install UI and MIDI libraries
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pynput", "pyautogui", "mido", "python-rtmidi", "--quiet"])
    print("[OK] Dependencies installed.")

try:
    from pynput import mouse
except ImportError:
    install_deps()
    from pynput import mouse

# Ensure MIDI library available
try:
    import mido
except Exception:
    # install_deps already installs mido; on failure, keep going and surface later
    mido = None


def list_midi_devices():
    """Return list of MIDI input device names (may be empty)."""
    if not mido:
        return []
    try:
        return mido.get_input_names()
    except Exception:
        return []

# ---------------------------------------------------------------------------
# Helper: wait for a single left-click release, return (x, y)
# ---------------------------------------------------------------------------
def get_click(prompt, ignore_first=False):
    print(f"\n[SETUP] {prompt}")
    print("       --> Click now...")
    pos = []
    def on_click(x, y, button, pressed):
        if button == mouse.Button.left and not pressed:
            pos.append((x, y))
            # If ignoring the first click, wait for a second release before stopping
            if ignore_first and len(pos) == 1:
                return None  # continue listening
            return False
    with mouse.Listener(on_click=on_click) as listener:
        listener.join()
    captured = pos[-1]
    print(f"       --> Captured: {captured}")
    return captured

# ---------------------------------------------------------------------------
# Calibration for one channel
# ---------------------------------------------------------------------------
def calibrate_channel(ch_num):
    print(f"\n{'='*50}")
    print(f"  CHANNEL {ch_num} CALIBRATION")
    print(f"{'='*50}")
    open_p  = get_click(f"Ch{ch_num}: Click the CFX dropdown ARROW (closed menu)")
    opt1_p  = get_click(f"Ch{ch_num}: OPEN the menu manually, then click OPTION 1 (the menu will close after selection)")
    opt9_p  = get_click(f"Ch{ch_num}: OPEN the menu manually again, then click OPTION 9 (last option - ensure the menu is open before clicking)", ignore_first=True)
    step_y  = (opt9_p[1] - opt1_p[1]) / 8.0
    return {
        "open":  list(open_p),
        "opt1":  list(opt1_p),
        "opt9":  list(opt9_p),
        "step_y": step_y
    }

# ---------------------------------------------------------------------------
# AHK script generator
# ---------------------------------------------------------------------------
AHK_HEADER = """#Requires AutoHotkey v2.0
; Note: #NoEnv is removed in AHK v2 — avoid directives from v1
SendMode("Input")
CoordMode("Mouse", "Screen")

; ============================================================
;  Rekordbox CFX Channel Selector (AHK v2)
;  Generated by setup_cfx.py  --  do not edit manually
; ============================================================

; CLICK_DELAY_MS controls the pause between clicks (adjust as needed)
CLICK_DELAY_MS := {click_delay}

; Modifier scheme:
;   Channel 1: Ctrl+Alt+1..9
;   Channel 2: Ctrl+Shift+1..9
;   Channel 3: Alt+Shift+1..9
;   Channel 4: Ctrl+Alt+Shift+1..9
;
; Map these keystrokes in Bome / MIDI Translator to your pads.

"""

AHK_FUNC = """
; ============================================================
;  Core click helper (AHK v2)
; ============================================================
ClickCFX(ox, oy, ty) {
    sx := 0
    sy := 0
    MouseGetPos(&sx, &sy)
    Click(ox, oy)
    Sleep CLICK_DELAY_MS
    Click(ox, ty)
    MouseMove(sx, sy, 0)
}
"""

MODIFIERS = {
    1: "^!",          # Ctrl+Alt
    2: "^+",          # Ctrl+Shift
    3: "!+",          # Alt+Shift
    4: "^!+",         # Ctrl+Alt+Shift
}

# Python dict (AHK comment block above is illustrative — real mapping below)
MODIFIERS_PY = {
    1: "^!",
    2: "^+",
    3: "!+",
    4: "^!+",
}

def generate_ahk(channels: dict, click_delay: int = 20) -> str:
    header = AHK_HEADER.format(click_delay=int(click_delay))
    lines = [header]
    for ch_num, cal in channels.items():
        ox   = cal["open"][0]
        oy   = cal["open"][1]
        y1   = cal["opt1"][1]
        step = cal["step_y"]
        mod  = MODIFIERS_PY[ch_num]
        lines.append(f"; --- Channel {ch_num}  (modifier: {mod}) ---")
        for i in range(1, 10):
            ty = round(y1 + (i - 1) * step)
            # AHK v2 hotkey syntax uses the same prefix strings (e.g. ^!1::)
            lines.append(f"{mod}{i}:: ClickCFX({ox}, {oy}, {ty})")
        lines.append("")
    lines.append(AHK_FUNC)
    return "\n".join(lines)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    import argparse
    parser = argparse.ArgumentParser(prog="setup_cfx.py", description="Calibration and AHK generator (minimal interactive CLI)")
    parser.add_argument("--channels", "-c", type=int, choices=range(1,5), help="Number of channels to calibrate (1-4)")
    parser.add_argument("--generate-from-json", action="store_true", help="Generate AHK from existing calibration JSON (uses cfx_calibration.json if no path provided)")
    parser.add_argument("--json-path", "-j", help="Path to calibration JSON to generate AHK from")
    parser.add_argument("--click-delay", "-d", type=int, default=20, help="Click delay in milliseconds to embed in generated AHK (default: 20)")
    parser.add_argument("--input-method", choices=["midi","keyboard"], help="Input method for triggering CFX selections")
    parser.add_argument("--midi-device", help="MIDI device name or numeric index to use (interactive will list devices)")
    parser.add_argument("--no-prompt", action="store_true", help="Run without intermediate prompts (useful for scripts)")
    args = parser.parse_args()

    # Non-interactive flows
    def _pick_midi_device(midi_arg=None):
        names = list_midi_devices()
        if not names:
            return None
        if midi_arg:
            # numeric index?
            try:
                idx = int(midi_arg)
                if 0 <= idx < len(names):
                    return names[idx]
            except Exception:
                pass
            # match by substring
            for n in names:
                if midi_arg.lower() in n.lower():
                    return n
            return None
        # no arg: pick first
        return names[0]

    if args.generate_from_json or args.json_path:
        cal_path = args.json_path if args.json_path else os.path.join(os.path.dirname(__file__), "cfx_calibration.json")
        if not os.path.exists(cal_path):
            print(f"[ERROR] Calibration JSON not found at {cal_path}")
            sys.exit(1)
        with open(cal_path, "r", encoding="utf-8") as f:
            channels = json.load(f)
            channels = {int(k): v for k, v in channels.items()}
        # Determine input method
        input_cfg = {"method": "keyboard", "device": None}
        if args.input_method == "midi" or args.midi_device:
            dev = _pick_midi_device(args.midi_device)
            if dev:
                input_cfg = {"method": "midi", "device": dev}
            else:
                print("[WARN] MIDI device not found; falling back to keyboard input")
        channels.setdefault("_meta", {})["input"] = input_cfg
        ahk_path = os.path.join(os.path.dirname(__file__), "RekordboxCFX.ahk")
        ahk_code = generate_ahk(channels, click_delay=args.click_delay)
        with open(ahk_path, "w", encoding="utf-8") as f:
            f.write(ahk_code)
        print(f"[OK] AHK script written to {ahk_path}")
        return

    if args.channels:
        n_channels = args.channels
        channels = {}
        for ch in range(1, n_channels + 1):
            channels[ch] = calibrate_channel(ch)
        # Ask for input method
        input_cfg = {"method": "keyboard", "device": None}
        if not args.no_prompt:
            im = input('Input method for triggers ([m]idi/[k]eyboard, default keyboard): ').strip().lower()
            if im.startswith('m'):
                names = list_midi_devices()
                if not names:
                    print('[WARN] No MIDI devices found; using keyboard input')
                else:
                    print('\nAvailable MIDI devices:')
                    for i, n in enumerate(names):
                        print(f'  {i}) {n}')
                    sel = input('Select device index (default 0): ').strip()
                    try:
                        sel_i = int(sel) if sel else 0
                        dev = names[sel_i]
                        input_cfg = {"method": "midi", "device": dev}
                    except Exception:
                        print('[WARN] Invalid selection; using keyboard input')
        else:
            if args.input_method == 'midi':
                dev = _pick_midi_device(args.midi_device)
                if dev:
                    input_cfg = {"method": "midi", "device": dev}
        cal_path = os.path.join(os.path.dirname(__file__), "cfx_calibration.json")
        channels.setdefault("_meta", {})["input"] = input_cfg
        with open(cal_path, "w", encoding="utf-8") as f:
            json.dump(channels, f, indent=2)
        print(f"\n[OK] Calibration saved to {cal_path}")
        ahk_path = os.path.join(os.path.dirname(__file__), "RekordboxCFX.ahk")
        ahk_code = generate_ahk(channels, click_delay=args.click_delay)
        with open(ahk_path, "w", encoding="utf-8") as f:
            f.write(ahk_code)
        print(f"[OK] AHK script written to {ahk_path}")
        return

    # Interactive menu
    while True:
        print('\n--- Rekordbox CFX Setup (interactive) ---')
        print('1) Calibrate channels')
        print('2) Generate AHK from existing calibration JSON')
        print('3) Show help')
        print('4) Quit')
        choice = input('Select an option [1-4]: ').strip()
        if choice == '1':
            try:
                n = int(input('How many channels to calibrate? (1-4): ').strip())
                assert 1 <= n <= 4
            except (ValueError, AssertionError):
                print('[ERROR] Enter a number between 1 and 4.')
                continue
            channels = {}
            for ch in range(1, n + 1):
                channels[ch] = calibrate_channel(ch)
            # Ask for input method (interactive)
            input_cfg = {"method": "keyboard", "device": None}
            if not args.no_prompt:
                im = input('Input method for triggers ([m]idi/[k]eyboard, default keyboard): ').strip().lower()
                if im.startswith('m'):
                    names = list_midi_devices()
                    if not names:
                        print('[WARN] No MIDI devices found; using keyboard input')
                    else:
                        print('\nAvailable MIDI devices:')
                        for i, n in enumerate(names):
                            print(f'  {i}) {n}')
                        sel = input('Select device index (default 0): ').strip()
                        try:
                            sel_i = int(sel) if sel else 0
                            dev = names[sel_i]
                            input_cfg = {"method": "midi", "device": dev}
                        except Exception:
                            print('[WARN] Invalid selection; using keyboard input')
            else:
                if args.input_method == 'midi':
                    dev = _pick_midi_device(args.midi_device)
                    if dev:
                        input_cfg = {"method": "midi", "device": dev}
            channels.setdefault("_meta", {})["input"] = input_cfg
            cal_path = os.path.join(os.path.dirname(__file__), "cfx_calibration.json")
            with open(cal_path, "w", encoding="utf-8") as f:
                json.dump(channels, f, indent=2)
            print(f"\n[OK] Calibration saved to {cal_path}")
            # Ask interactive user for click delay unless no-prompt is set
            if not args.no_prompt:
                try:
                    dd = input('Click delay in ms (default 20): ').strip()
                    click_delay = int(dd) if dd else args.click_delay
                except Exception:
                    click_delay = args.click_delay
            else:
                click_delay = args.click_delay
            ahk_path = os.path.join(os.path.dirname(__file__), "RekordboxCFX.ahk")
            ahk_code = generate_ahk(channels, click_delay=click_delay)
            with open(ahk_path, "w", encoding="utf-8") as f:
                f.write(ahk_code)
            print(f"[OK] AHK script written to {ahk_path}")
        elif choice == '2':
            p = input('Path to calibration JSON (leave empty for cfx_calibration.json): ').strip()
            cal_path = p if p else os.path.join(os.path.dirname(__file__), "cfx_calibration.json")
            if not os.path.exists(cal_path):
                print(f"[ERROR] Calibration JSON not found at {cal_path}")
                continue
            with open(cal_path, "r", encoding="utf-8") as f:
                channels = json.load(f)
                channels = {int(k): v for k, v in channels.items()}
            # Ask interactive user for input method
            input_cfg = {"method": "keyboard", "device": None}
            if not args.no_prompt:
                im = input('Input method for triggers ([m]idi/[k]eyboard, default keyboard): ').strip().lower()
                if im.startswith('m'):
                    names = list_midi_devices()
                    if not names:
                        print('[WARN] No MIDI devices found; using keyboard input')
                    else:
                        print('\nAvailable MIDI devices:')
                        for i, n in enumerate(names):
                            print(f'  {i}) {n}')
                        sel = input('Select device index (default 0): ').strip()
                        try:
                            sel_i = int(sel) if sel else 0
                            dev = names[sel_i]
                            input_cfg = {"method": "midi", "device": dev}
                        except Exception:
                            print('[WARN] Invalid selection; using keyboard input')
            else:
                if args.input_method == 'midi':
                    dev = _pick_midi_device(args.midi_device)
                    if dev:
                        input_cfg = {"method": "midi", "device": dev}
            channels.setdefault("_meta", {})["input"] = input_cfg
            # Ask interactive user for click delay unless no-prompt is set
            if not args.no_prompt:
                try:
                    dd = input('Click delay in ms (default 20): ').strip()
                    click_delay = int(dd) if dd else args.click_delay
                except Exception:
                    click_delay = args.click_delay
            else:
                click_delay = args.click_delay
            ahk_path = os.path.join(os.path.dirname(__file__), "RekordboxCFX.ahk")
            ahk_code = generate_ahk(channels, click_delay=click_delay)
            with open(ahk_path, "w", encoding="utf-8") as f:
                f.write(ahk_code)
            print(f"[OK] AHK script written to {ahk_path}")
        elif choice == '3':
            parser.print_help()
        elif choice == '4':
            print('Goodbye.')
            break
        else:
            print('[ERROR] Invalid selection.')

    print()
    print("╔══════════════════════════════════════════════╗")
    print("║   Rekordbox CFX Selector  –  Setup Wizard   ║")
    print("╚══════════════════════════════════════════════╝")
    print()

    # If called with --generate-from-json, load existing calibration and write AHK
    if len(sys.argv) > 1 and sys.argv[1] == "--generate-from-json":
        cal_path = os.path.join(os.path.dirname(__file__), "cfx_calibration.json")
        if not os.path.exists(cal_path):
            print(f"[ERROR] Calibration JSON not found at {cal_path}")
            sys.exit(1)
        with open(cal_path, "r", encoding="utf-8") as f:
            channels = json.load(f)
            # keys might be strings; convert to int keys
            channels = {int(k): v for k, v in channels.items()}
        ahk_path = os.path.join(os.path.dirname(__file__), "RekordboxCFX.ahk")
        ahk_code = generate_ahk(channels)
        with open(ahk_path, "w", encoding="utf-8") as f:
            f.write(ahk_code)
        print(f"[OK] AHK script written to {ahk_path}")
        sys.exit(0)

    try:
        n_channels = int(input("How many channels to calibrate? (1–4): ").strip())
        assert 1 <= n_channels <= 4
    except (ValueError, AssertionError):
        print("[ERROR] Enter a number between 1 and 4.")
        sys.exit(1)

    channels = {}
    for ch in range(1, n_channels + 1):
        channels[ch] = calibrate_channel(ch)

    # Save calibration JSON (for re-runs / debugging)
    cal_path = os.path.join(os.path.dirname(__file__), "cfx_calibration.json")
    with open(cal_path, "w", encoding="utf-8") as f:
        json.dump(channels, f, indent=2)
    print(f"\n[OK] Calibration saved to {cal_path}")

    # Write AHK script
    ahk_path = os.path.join(os.path.dirname(__file__), "RekordboxCFX.ahk")
    ahk_code = generate_ahk(channels)
    with open(ahk_path, "w", encoding="utf-8") as f:
        f.write(ahk_code)
    print(f"[OK] AHK script written to {ahk_path}")
    print()
    print("Next step: run setup_cfx.bat  (or the EXE will be compiled automatically)")

if __name__ == "__main__":
    main()
