import os, sys, subprocess, json

# ---------------------------------------------------------------------------
# Dependency bootstrap
# ---------------------------------------------------------------------------
def install_deps():
    print("[SETUP] Installing Python dependencies...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pynput", "pyautogui", "--quiet"])
    print("[OK] Dependencies installed.")

try:
    from pynput import mouse
except ImportError:
    install_deps()
    from pynput import mouse

# ---------------------------------------------------------------------------
# Helper: wait for a single left-click release, return (x, y)
# ---------------------------------------------------------------------------
def get_click(prompt):
    print(f"\n[SETUP] {prompt}")
    print("       --> Click now...")
    pos = []
    def on_click(x, y, button, pressed):
        if button == mouse.Button.left and not pressed:
            pos.append((x, y))
            return False
    with mouse.Listener(on_click=on_click) as listener:
        listener.join()
    print(f"       --> Captured: {pos[0]}")
    return pos[0]

# ---------------------------------------------------------------------------
# Calibration for one channel
# ---------------------------------------------------------------------------
def calibrate_channel(ch_num):
    print(f"\n{'='*50}")
    print(f"  CHANNEL {ch_num} CALIBRATION")
    print(f"{'='*50}")
    open_p  = get_click(f"Ch{ch_num}: Click the CFX dropdown ARROW (closed menu)")
    opt1_p  = get_click(f"Ch{ch_num}: OPEN the menu manually, then click OPTION 1 (the menu will close after selection)")
    opt9_p  = get_click(f"Ch{ch_num}: OPEN the menu manually again, then click OPTION 9 (last option - ensure the menu is open before clicking)")
    step_y  = (opt9_p[1] - opt1_p[1]) / 8.0
    return {
        "open":  list(open_p),
        "opt1":  list(opt1_p),
        "opt9":  list(opt9_p),
        "step_y": step_y
    }

# ---------------------------------------------------------------------------
# AHK script generator
# ---------------------------------------------------------------------------
AHK_HEADER = """#NoEnv
SetControlDelay, -1
SetBatchLines, -1
SendMode Input
CoordMode, Mouse, Screen

; ============================================================
;  Rekordbox CFX Channel Selector
;  Generated by setup_cfx.py  --  do not edit manually
; ============================================================

; Modifier scheme:
;   Channel 1: Ctrl+Alt+1..9
;   Channel 2: Ctrl+Shift+1..9
;   Channel 3: Alt+Shift+1..9
;   Channel 4: Ctrl+Alt+Shift+1..9
;
; Map these keystrokes in Bome / MIDI Translator to your pads.

"""

AHK_FUNC = """
; ============================================================
;  Core click helper
; ============================================================
ClickCFX(ox, oy, ty) {
    MouseGetPos, sx, sy
    Click, %ox%, %oy%
    Sleep, 20
    Click, %ox%, %ty%
    MouseMove, %sx%, %sy%, 0
}
"""

MODIFIERS = {
    1: "^!",          # Ctrl+Alt
    2: "^+",          # Ctrl+Shift
    3: "!+",          # Alt+Shift
    4: "^!+",         # Ctrl+Alt+Shift
}

# Python dict (AHK comment block above is illustrative — real mapping below)
MODIFIERS_PY = {
    1: "^!",
    2: "^+",
    3: "!+",
    4: "^!+",
}

def generate_ahk(channels: dict) -> str:
    lines = [AHK_HEADER]
    for ch_num, cal in channels.items():
        ox   = cal["open"][0]
        oy   = cal["open"][1]
        y1   = cal["opt1"][1]
        step = cal["step_y"]
        mod  = MODIFIERS_PY[ch_num]
        lines.append(f"; --- Channel {ch_num}  (modifier: {mod}) ---")
        for i in range(1, 10):
            ty = round(y1 + (i - 1) * step)
            lines.append(f"{mod}{i}:: ClickCFX({ox}, {oy}, {ty})")
        lines.append("")
    lines.append(AHK_FUNC)
    return "\n".join(lines)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print()
    print("╔══════════════════════════════════════════════╗")
    print("║   Rekordbox CFX Selector  –  Setup Wizard   ║")
    print("╚══════════════════════════════════════════════╝")
    print()

    try:
        n_channels = int(input("How many channels to calibrate? (1–4): ").strip())
        assert 1 <= n_channels <= 4
    except (ValueError, AssertionError):
        print("[ERROR] Enter a number between 1 and 4.")
        sys.exit(1)

    channels = {}
    for ch in range(1, n_channels + 1):
        channels[ch] = calibrate_channel(ch)

    # Save calibration JSON (for re-runs / debugging)
    cal_path = os.path.join(os.path.dirname(__file__), "cfx_calibration.json")
    with open(cal_path, "w", encoding="utf-8") as f:
        json.dump(channels, f, indent=2)
    print(f"\n[OK] Calibration saved to {cal_path}")

    # Write AHK script
    ahk_path = os.path.join(os.path.dirname(__file__), "RekordboxCFX.ahk")
    ahk_code = generate_ahk(channels)
    with open(ahk_path, "w", encoding="utf-8") as f:
        f.write(ahk_code)
    print(f"[OK] AHK script written to {ahk_path}")
    print()
    print("Next step: run setup_cfx.bat  (or the EXE will be compiled automatically)")

if __name__ == "__main__":
    main()
